/// Inspects what a file can actually prove about its own origin.
///
/// **The scientific limit, honoured.** This does not, and will not, say "93%
/// chance this was generated by AI". Text AI-detection is not reliable enough
/// to support that claim, image detection barely more so, and a false positive
/// here is not an inconvenience — it is an accusation against a real person.
/// Any product that prints such a percentage is selling confidence it does not
/// have.
///
/// So this reports *evidence*, and where the evidence is thin it says so.
/// Returning [AuthenticityVerdict.inconclusive] is the correct answer for most
/// files, and the tests assert that it happens.
///
/// **What it reads.** Local file metadata only: EXIF, declared camera and
/// software, GPS presence, and structural signals. No network, no model, no
/// key. It works with no provider connected.
///
/// **What it cannot read.** C2PA / Content Credentials require cryptographic
/// verification, and there is no Flutter binding for it — only a Kotlin AAR over
/// the Rust SDK. [ProvenanceVerifier] is the seam a native channel would slot
/// into. Until one exists, Action reports that provenance was not checked; it
/// never implies it was.
///
/// See `docs/v2/ACTION_INTELLIGENCE_SPEC.md` §7.
library;

import 'dart:typed_data';

import 'package:image/image.dart' as img;

/// The only verdicts this tool may reach.
///
/// Note what is absent: nothing here expresses a probability, and there is no
/// verdict meaning "definitely AI".
enum AuthenticityVerdict {
  /// A cryptographic provenance signature was verified.
  verifiedProvenanceAvailable,

  /// Metadata declares a known generative tool. Evidence of a claim the file
  /// makes about itself — not proof, since metadata is trivially editable.
  signalsConsistentWithSynthetic,

  /// Metadata declares editing software.
  signalsConsistentWithEdited,

  /// Metadata is absent or stripped. Extremely common and means very little:
  /// most platforms strip EXIF on upload.
  noReliableProvenanceFound,

  /// Not enough to say anything.
  inconclusive,
}

String describeVerdict(AuthenticityVerdict verdict) => switch (verdict) {
      AuthenticityVerdict.verifiedProvenanceAvailable =>
        'Verified provenance available',
      AuthenticityVerdict.signalsConsistentWithSynthetic =>
        'Signals consistent with AI-generated content',
      AuthenticityVerdict.signalsConsistentWithEdited =>
        'Signals consistent with edited content',
      AuthenticityVerdict.noReliableProvenanceFound =>
        'No reliable provenance found',
      AuthenticityVerdict.inconclusive => 'Inconclusive',
    };

/// The sentence under the verdict. Every one of these limits the claim.
String explainVerdict(AuthenticityVerdict verdict) => switch (verdict) {
      AuthenticityVerdict.verifiedProvenanceAvailable =>
        'This file carries a signature that was checked and held up.',
      AuthenticityVerdict.signalsConsistentWithSynthetic =>
        'This file says it was made with a generative tool. Metadata can be '
            'edited or removed, so this is what the file claims, not proof.',
      AuthenticityVerdict.signalsConsistentWithEdited =>
        'This file says it passed through editing software. That is ordinary '
            'for photographs and does not by itself mean anything was faked.',
      AuthenticityVerdict.noReliableProvenanceFound =>
        'There is no provenance information in this file. That is normal — most '
            'services strip it — and it is not a sign of anything.',
      AuthenticityVerdict.inconclusive =>
        'There is not enough information here to say where this came from.',
    };

/// One thing that was found, or looked for and not found.
class AuthenticitySignal {
  const AuthenticitySignal({
    required this.label,
    required this.value,
    this.experimental = false,
  });

  final String label;
  final String value;

  /// Marked in the UI. An experimental signal must never carry the weight of a
  /// verified one.
  final bool experimental;
}

class AuthenticityReport {
  const AuthenticityReport({
    required this.verdict,
    required this.signals,
    this.provenanceChecked = false,
  });

  final AuthenticityVerdict verdict;
  final List<AuthenticitySignal> signals;

  /// Whether a cryptographic verifier actually ran. False means "not checked",
  /// which is reported as such rather than as "nothing found".
  final bool provenanceChecked;
}

/// The seam a native C2PA implementation would fill.
abstract interface class ProvenanceVerifier {
  /// Null when no verifier is installed — distinct from "checked, found
  /// nothing", which would be a stronger claim than Action can make.
  Future<AuthenticitySignal?> verify(Uint8List bytes);
}

/// The default: no cryptographic verification is available.
class UnavailableProvenanceVerifier implements ProvenanceVerifier {
  const UnavailableProvenanceVerifier();

  @override
  Future<AuthenticitySignal?> verify(Uint8List bytes) async => null;
}

abstract final class AuthenticityInspector {
  /// Software strings that name a generative tool.
  ///
  /// A declaration, not a detection. Matching one means the file says it was
  /// made this way; not matching means nothing at all, because the field is
  /// trivially removed.
  static const _generativeMarkers = [
    'stable diffusion',
    'midjourney',
    'dall-e',
    'dalle',
    'firefly',
    'imagen',
    'flux',
    'comfyui',
    'automatic1111',
    'invokeai',
    'nano banana',
    'gpt-image',
    'sora',
  ];

  static const _editingMarkers = [
    'photoshop',
    'lightroom',
    'gimp',
    'affinity',
    'pixelmator',
    'snapseed',
    'capture one',
    'luminar',
  ];

  static Future<AuthenticityReport> inspectImage(
    Uint8List bytes, {
    ProvenanceVerifier verifier = const UnavailableProvenanceVerifier(),
  }) async {
    final signals = <AuthenticitySignal>[];

    final provenance = await verifier.verify(bytes);
    if (provenance != null) {
      return AuthenticityReport(
        verdict: AuthenticityVerdict.verifiedProvenanceAvailable,
        signals: [provenance, ...signals],
        provenanceChecked: true,
      );
    }

    final img.Image? decoded;
    try {
      decoded = img.decodeImage(bytes);
    } on Object {
      return const AuthenticityReport(
        verdict: AuthenticityVerdict.inconclusive,
        signals: [
          AuthenticitySignal(
            label: 'File',
            value: 'Could not be read as an image.',
          ),
        ],
      );
    }

    if (decoded == null) {
      return const AuthenticityReport(
        verdict: AuthenticityVerdict.inconclusive,
        signals: [
          AuthenticitySignal(
            label: 'File',
            value: 'Not a recognised image format.',
          ),
        ],
      );
    }

    final exif = decoded.exif;
    final make = _clean(exif.imageIfd.make);
    final model = _clean(exif.imageIfd.model);
    final software = _clean(exif.imageIfd.software);
    final description = _clean(exif.imageIfd.imageDescription);
    final copyright = _clean(exif.imageIfd.copyright);
    final hasGps = exif.gpsIfd.keys.isNotEmpty;

    if (make != null || model != null) {
      signals.add(AuthenticitySignal(
        label: 'Camera',
        value: [?make, ?model].join(' ').trim(),
      ));
    }
    if (software != null) {
      signals.add(AuthenticitySignal(label: 'Software', value: software));
    }
    if (description != null) {
      signals.add(AuthenticitySignal(label: 'Description', value: description));
    }
    if (copyright != null) {
      signals.add(AuthenticitySignal(label: 'Copyright', value: copyright));
    }
    if (hasGps) {
      // Presence only. Action does not display someone's coordinates back at
      // them in a tool about authenticity.
      signals.add(const AuthenticitySignal(
        label: 'Location',
        value: 'Location data is present in this file.',
      ));
    }
    signals.add(const AuthenticitySignal(
      label: 'Content Credentials',
      value: 'Not checked — this build has no signature verifier.',
    ));

    final haystack = [?software, ?description, ?make, ?model]
        .join(' ')
        .toLowerCase();

    if (_generativeMarkers.any(haystack.contains)) {
      return AuthenticityReport(
        verdict: AuthenticityVerdict.signalsConsistentWithSynthetic,
        signals: signals,
      );
    }
    if (_editingMarkers.any(haystack.contains)) {
      return AuthenticityReport(
        verdict: AuthenticityVerdict.signalsConsistentWithEdited,
        signals: signals,
      );
    }
    // A camera make and model with GPS is the strongest ordinary evidence a
    // file offers — and it is still only "consistent with a photograph", which
    // is why it does not get its own confident verdict.
    if (make != null && model != null) {
      return AuthenticityReport(
        verdict: AuthenticityVerdict.inconclusive,
        signals: signals,
      );
    }
    if (signals.length <= 1) {
      return AuthenticityReport(
        verdict: AuthenticityVerdict.noReliableProvenanceFound,
        signals: signals,
      );
    }
    return AuthenticityReport(
      verdict: AuthenticityVerdict.inconclusive,
      signals: signals,
    );
  }

  /// Text has no provenance to inspect, and there is no honest verdict to give.
  ///
  /// This deliberately always returns [AuthenticityVerdict.inconclusive].
  /// Saying so is a feature: a product that tells a teacher a student's essay
  /// is 93% AI is wrong often enough to ruin someone, and being unable to
  /// answer is the truthful state of the art.
  static AuthenticityReport inspectText(String text) => const AuthenticityReport(
        verdict: AuthenticityVerdict.inconclusive,
        signals: [
          AuthenticitySignal(
            label: 'Text',
            value: 'Text alone cannot reliably show whether AI was used. '
                'Action does not guess.',
            experimental: true,
          ),
        ],
      );

  static String? _clean(String? value) {
    final text = value?.trim();
    if (text == null || text.isEmpty) return null;
    // Some encoders pad fixed-width EXIF strings with NUL bytes. Written as
    // an escape rather than a literal, which would make this source file
    // binary to every tool that reads it.
    final stripped = text.replaceAll('\x00', '').trim();
    return stripped.isEmpty ? null : stripped;
  }
}
