/// The bottom navigation labels fit, in every language, as rendered.
///
/// **The defect this holds.** On the emulator, the Japanese Intelligence tab
/// read 「インテリジ…」: eight full-width characters in a slot that holds six.
/// Nothing caught it because nothing could — `flutter test` shapes every glyph
/// with the FlutterTest font, in which a Latin letter, a Thai tone mark and a
/// kanji are all one em wide, so "does this label fit?" had no true answer in
/// a widget test. A character budget would not have been an answer either:
/// Thai fits at thirteen code points where Japanese does not fit at eight.
///
/// **How it measures.** The production shell is built through the production
/// router, and the text is shaped with the fonts the QA device actually draws
/// it with: Roboto for Latin and Cyrillic, and the Noto faces Android falls
/// back to for Arabic, Bengali, Devanagari, Thai and the CJK scripts. They are
/// subsets under `test/fonts/`, regenerated by `tool/qa_fonts/subset_qa_fonts.py`.
/// The only thing the test changes about the theme is the font family list;
/// sizes, weights, paddings and the bar's geometry are the shipped ones.
///
/// **What "fits" means here.** The label's own `RenderParagraph` reports
/// whether it exceeded its one allowed line — the exact condition under which
/// the framework draws the ellipsis. Nothing is estimated.
library;

import 'dart:io';

import 'package:action_app/app/action_shell.dart';
import 'package:action_app/app/router.dart';
import 'package:action_app/core/preferences/preference_store.dart';
import 'package:action_app/core/preferences/shared_preferences_store.dart';
import 'package:action_app/design/app_theme.dart';
import 'package:action_app/features/actions/application/action_providers.dart';
import 'package:action_app/features/actions/data/action_cloud_mirror.dart';
import 'package:action_app/features/actions/data/actions_database.dart';
import 'package:action_app/features/actions/data/auth_identity_service.dart';
import 'package:action_app/features/capture/application/capture_controller.dart';
import 'package:action_app/features/capture/data/ocr_service.dart';
import 'package:action_app/l10n/gen/app_l10n.dart';
import 'package:action_app/l10n/supported_locales.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

import '../actions/support/actions_test_support.dart';
import '../actions/support/fake_notification_scheduler.dart';
import '../support/fake_stores.dart';

class _NoIdentity implements AuthIdentityService {
  const _NoIdentity();
  @override
  String? get lastFailureClass => 'auth_unavailable';
  @override
  Future<String?> currentOrSignInUid() async => null;
}

/// The device fonts, by the family name the test theme refers to them by.
///
/// Two weights of each variable face are pinned separately because the
/// engine's dynamic font manager matches a requested weight to the nearest
/// registered face; it does not drive a variation axis.
const _families = <String, List<String>>{
  'QaLatin': ['Roboto-w500.ttf', 'Roboto-w600.ttf'],
  'QaThai': ['NotoSansThai-Regular.ttf', 'NotoSansThai-Bold.ttf'],
  'QaBengali': ['NotoSansBengali-w500.ttf', 'NotoSansBengali-w600.ttf'],
  'QaDevanagari': [
    'NotoSansDevanagari-w500.ttf',
    'NotoSansDevanagari-w600.ttf',
  ],
  'QaArabic': [
    'NotoNaskhArabicUI-Regular.ttf',
    'NotoNaskhArabicUI-Bold.ttf',
  ],
  'QaCjk': ['NotoSansCJK-Regular.otf'],
};

Future<void> _loadDeviceFonts() async {
  for (final entry in _families.entries) {
    final loader = FontLoader(entry.key);
    for (final file in entry.value) {
      final bytes = await File('test/fonts/$file').readAsBytes();
      loader.addFont(Future.value(bytes.buffer.asByteData()));
    }
    await loader.load();
  }
}

/// The shipped theme with only its font resolution changed.
ThemeData _withDeviceFonts(ThemeData theme) {
  return theme.copyWith(
    textTheme: theme.textTheme.apply(
      fontFamily: 'QaLatin',
      fontFamilyFallback: _families.keys.where((f) => f != 'QaLatin').toList(),
    ),
  );
}

/// Phone widths in logical pixels, narrowest first. 360 is the floor for the
/// devices Action targets; 393 and 412 are the common Pixel widths, including
/// the QA emulator's.
const _widths = [360.0, 393.0, 412.0];

late ActionsDatabase _db;
late FakeNotificationScheduler _scheduler;

/// Pumps the production router — and therefore the production shell and nav
/// bar — speaking [locale], at [width] logical pixels and [textScale].
Future<void> _pumpShell(
  WidgetTester tester, {
  required Locale locale,
  required double width,
  double textScale = 1.0,
  bool dark = false,
}) async {
  tester.view.physicalSize = Size(width, 800);
  tester.view.devicePixelRatio = 1.0;
  tester.platformDispatcher.textScaleFactorTestValue = textScale;

  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        preferenceStoreProvider.overrideWithValue(
          InMemoryPreferenceStore({PreferenceKeys.onboardingCompleted: true}),
        ),
        actionsDatabaseProvider.overrideWithValue(_db),
        sourceStoreProvider.overrideWith((ref) async => FakeSourceStore()),
        sourceFileStoreProvider
            .overrideWith((ref) async => FakeSourceFileStore()),
        ocrServiceProvider.overrideWithValue(const FakeOcrService()),
        authIdentityServiceProvider.overrideWithValue(const _NoIdentity()),
        actionCloudMirrorProvider
            .overrideWithValue(const NoopActionCloudMirror()),
        notificationSchedulerProvider.overrideWithValue(_scheduler),
      ],
      child: Consumer(
        builder: (context, ref, _) => MaterialApp.router(
          theme: _withDeviceFonts(dark ? AppTheme.dark() : AppTheme.light()),
          locale: locale,
          localizationsDelegates: const [
            AppL10n.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: AppLocales.locales,
          localeListResolutionCallback: AppLocales.resolve,
          routerConfig: ref.watch(routerProvider),
          debugShowCheckedModeBanner: false,
        ),
      ),
    ),
  );
  await tester.pumpAndSettle();
}

/// The paragraph that draws one destination's label.
///
/// Found through the tooltip the production `_NavItem` wraps every
/// destination in, so a page that happens to contain the same word — Today's
/// own title, say — cannot be mistaken for the bar.
RenderParagraph _labelParagraph(WidgetTester tester, String label) {
  final tooltip = find.byWidgetPredicate(
    (w) => w is Tooltip && w.message == label,
  );
  expect(tooltip, findsOneWidget, reason: 'nav item "$label" not on screen');
  // The item also draws an icon, which is a RichText of its own; the label
  // is the one Text widget under the tooltip.
  final text = find.descendant(of: tooltip, matching: find.byType(Text));
  expect(text, findsOneWidget);
  final rich = find.descendant(of: text, matching: find.byType(RichText));
  return tester.renderObject<RenderParagraph>(rich);
}

/// Asserts every destination label rendered on one line without an ellipsis.
void _expectAllLabelsFit(
  WidgetTester tester, {
  required SupportedLanguage language,
  required double width,
  required double textScale,
}) {
  final l10n = lookupAppL10n(language.locale);
  for (final destination in shellDestinations) {
    final label = destination.label(l10n);
    final paragraph = _labelParagraph(tester, label);
    final drawn = paragraph.textSize.width;
    final available = paragraph.size.width;
    expect(
      paragraph.didExceedMaxLines,
      isFalse,
      reason:
          '${language.englishName} (${language.tag}) nav label "$label" '
          'ellipsizes at ${width.toInt()} dp, text scale $textScale: '
          'needs ${drawn.toStringAsFixed(1)} px, has '
          '${available.toStringAsFixed(1)} px. If the label was recently '
          'changed to use a character outside test/fonts, re-run '
          'tool/qa_fonts/subset_qa_fonts.py before shortening it.',
    );
    expect(
      tester.takeException(),
      isNull,
      reason: 'the shell threw while laying out ${language.tag}',
    );
  }
}

void main() {
  setUpAll(_loadDeviceFonts);

  setUp(() {
    _db = memoryDatabase();
    _scheduler = FakeNotificationScheduler();
  });

  tearDown(() {
    _scheduler.dispose();
    return _db.close();
  });

  void shellTest(
    String description,
    Future<void> Function(WidgetTester tester) body,
  ) {
    testWidgets(description, (tester) async {
      try {
        await body(tester);
      } finally {
        await tester.pumpWidget(const SizedBox.shrink());
        await tester.pump(const Duration(seconds: 5));
        tester.platformDispatcher.clearTextScaleFactorTestValue();
        tester.view.reset();
      }
    });
  }

  group('the device fonts are real', () {
    // If the loader silently fell back to the test font the whole file would
    // pass for the wrong reason: every Latin label would measure wider, and a
    // Thai label with five combining marks would measure nearly twice its
    // real width — so the assertions below would be *stricter* than the
    // device, not looser. This pins that the fonts loaded at all: in the
    // test font "iiii" and "MMMM" are the same width, and in Roboto they are
    // not.
    testWidgets('Roboto shaped the Latin text', (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          theme: _withDeviceFonts(AppTheme.light()),
          // Inside a Material, so the text inherits the theme's body style
          // and with it the family list under test.
          home: const Material(
            child: Row(children: [Text('iiii'), Text('MMMM')]),
          ),
        ),
      );
      final narrow = tester.getSize(find.text('iiii')).width;
      final wide = tester.getSize(find.text('MMMM')).width;
      expect(wide, greaterThan(narrow * 1.5));
    });

    testWidgets('a Thai combining mark does not advance', (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          theme: _withDeviceFonts(AppTheme.light()),
          home: const Material(
            // Same base consonants; the second carries two marks above.
            child: Row(children: [Text('คลง'), Text('คลั้ง')]),
          ),
        ),
      );
      final base = tester.getSize(find.text('คลง')).width;
      final marked = tester.getSize(find.text('คลั้ง')).width;
      expect(marked, closeTo(base, base * 0.05));
    });
  });

  group('every shipped language fits the bar', () {
    for (final width in _widths) {
      shellTest('at ${width.toInt()} dp, both themes', (tester) async {
        for (final language in AppLocales.all) {
          for (final dark in [false, true]) {
            await _pumpShell(
              tester,
              locale: language.locale,
              width: width,
              dark: dark,
            );
            _expectAllLabelsFit(
              tester,
              language: language,
              width: width,
              textScale: 1.0,
            );
          }
        }
      });
    }
  });

  group('the stressed scripts, at the widths and scale that found the bug', () {
    // The seven the device QA singled out: full-width CJK, a Thai label
    // carrying stacked marks, the two longest Latin and Cyrillic words, a
    // Bengali conjunct-heavy label, and the two RTL scripts.
    const stressedTags = ['ja', 'th', 'de', 'ru', 'bn', 'ar', 'ur'];
    final stressed = [
      for (final tag in stressedTags)
        AppLocales.all.singleWhere((l) => l.tag == tag),
    ];

    shellTest('fit at 360 dp with text scaled to 1.15', (tester) async {
      // Android's first "Large" step. A nav label that only fits at the
      // default size is a label that fails for the people most likely to
      // need it.
      for (final language in stressed) {
        await _pumpShell(
          tester,
          locale: language.locale,
          width: 360,
          textScale: 1.15,
        );
        _expectAllLabelsFit(
          tester,
          language: language,
          width: 360,
          textScale: 1.15,
        );
      }
    });

    shellTest('labels with room to spare do follow the system text size',
        (tester) async {
      // The bar holds labels at the size that fits rather than ellipsizing
      // them, and this pins that it is a ceiling, not a switch: a language
      // whose labels have slack must actually come out larger at 1.15.
      const japanese = Locale('ja');
      await _pumpShell(tester, locale: japanese, width: 412);
      final l10n = lookupAppL10n(japanese);
      final atDefault = _labelParagraph(tester, l10n.navToday).textSize.width;
      await _pumpShell(tester, locale: japanese, width: 412, textScale: 1.15);
      final atLarge = _labelParagraph(tester, l10n.navToday).textSize.width;
      expect(atLarge, greaterThan(atDefault * 1.1));
    });

    shellTest('at 200% text every language still shows its whole label',
        (tester) async {
      // The accessibility ceiling. The labels stop growing when the bar is
      // full, so the whole word stays readable and the tooltip and the
      // semantics label carry it in full; nothing is cut to "Intel…".
      for (final language in AppLocales.all) {
        await _pumpShell(
          tester,
          locale: language.locale,
          width: 360,
          textScale: 2.0,
        );
        _expectAllLabelsFit(
          tester,
          language: language,
          width: 360,
          textScale: 2.0,
        );
      }
    });

    shellTest('the Japanese label that shipped truncated now fits',
        (tester) async {
      const japanese = Locale('ja');
      await _pumpShell(tester, locale: japanese, width: 412);
      final l10n = lookupAppL10n(japanese);
      // The eight-character form ellipsized on the device at exactly this
      // width. Pin that the shipped label is not it, and that it fits.
      expect(l10n.navIntelligence, isNot('インテリジェンス'));
      final paragraph = _labelParagraph(tester, l10n.navIntelligence);
      expect(paragraph.didExceedMaxLines, isFalse);
    });
  });
}
